server:
  port: 8080
  app:
    token: ${SERVER_TOKEN}
sample:
  api:
    url: "http://localhost:8081/api"
resilience4j:
  circuitbreaker:
    configs:
      default:
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 5000
        waitDurationInOpenState: 5s
        minimumNumberOfCalls: 5
    instances:
      test-circuit:
        baseConfig: default
  bulkhead:
    instances:
      test-circuit:
        maxConcurrentCalls: 2
        maxWaitDuration: 0
  retry:
    instances:
      test-circuit:
        maxRetryAttempts: 3
        waitDuration: 500ms
        retryExceptions: [org.springframework.web.client.HttpServerErrorException,io.github.resilience4j.circuitbreaker.Exception]

